name: build-overlay

on:
  workflow_dispatch:
  push:

jobs:
  build-overlay:
    runs-on: ubuntu-24.04
    env:
      ROS_DISTRO: one
      DEB_DISTRO: bookworm
      UPSTREAM: https://raw.githubusercontent.com/v4hn/ros-o-builder/bookworm-one-unstable/repository
    steps:
      - uses: v4hn/ros-deb-builder-action@roso-noble
        with:
          ROS_DISTRO: ${{ env.ROS_DISTRO }}
          DEB_DISTRO: ${{ env.DEB_DISTRO }}
          BRANCH: ${{ github.ref_name }}-${{ env.DEB_DISTRO }}-${{ env.ROS_DISTRO }}
          REPOS_FILE: sources.repos
          ROSDEP_SOURCE: |
            rosdep.yaml
            ${{ env.UPSTREAM }}/local.yaml
          DEB_REPOSITORY: |
            deb [trusted=yes] ${{ env.UPSTREAM }} ./
          SBUILD_CONF: |
            $enable_network = 1;
            $dpkg_buildpackage_user_options = ['--jobs=3'];
          CONTINUE_ON_ERROR: true
          PUSH_ON_ERROR: true
          SQUASH_HISTORY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
